-- VibeSafe core tables — reproduces the tables/functions the dashboard depends
-- on that predate the other setup scripts: scans, vibesafe_plans, teams,
-- team_members, helper functions, and the admin get_user_activity() report.
-- Idempotent: safe to run on a fresh Supabase project or re-run on the live one.
-- (Captured from the live schema on 2026-07-06.)

-- ── SCAN HISTORY (written client-side by the dashboard) ──
create table if not exists scans (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  user_id      uuid,
  language     text,
  score        smallint,
  issues_count smallint,
  summary      text,
  results      jsonb
);
alter table scans enable row level security;
drop policy if exists "Users can view own scans" on scans;
create policy "Users can view own scans" on scans for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own scans" on scans;
create policy "Users can insert own scans" on scans for insert with check (auth.uid() = user_id);
drop policy if exists "Users can delete own scans" on scans;
create policy "Users can delete own scans" on scans for delete using (auth.uid() = user_id);

-- ── PLANS (written server-side by the Stripe webhook) ──
create table if not exists vibesafe_plans (
  id                     uuid primary key,
  plan                   text not null default 'free',
  upgraded_at            timestamptz,
  stripe_customer_id     text,
  stripe_subscription_id text,
  updated_at             timestamptz default now()
);
alter table vibesafe_plans enable row level security;
drop policy if exists "Users can read own plan" on vibesafe_plans;
create policy "Users can read own plan" on vibesafe_plans for select using (auth.uid() = id);

-- ── TEAMS ──
create table if not exists teams (
  id         uuid primary key default gen_random_uuid(),
  owner_id   uuid not null,
  name       text not null default 'My Team',
  created_at timestamptz default now()
);

create table if not exists team_members (
  id            uuid primary key default gen_random_uuid(),
  team_id       uuid not null,
  user_id       uuid,
  invited_email text not null,
  invited_by    uuid,
  role          text not null default 'member',
  status        text not null default 'pending',
  created_at    timestamptz default now(),
  invite_token  text
);

create or replace function public.is_team_member(_team_id uuid, _user_id uuid)
returns boolean language sql stable security definer set search_path to 'public'
as $$
  select exists (
    select 1 from team_members
    where team_id = _team_id and user_id = _user_id and status = 'active'
  );
$$;

create or replace function public.is_team_owner(_team_id uuid, _user_id uuid)
returns boolean language sql stable security definer set search_path to 'public'
as $$
  select exists (
    select 1 from teams
    where id = _team_id and owner_id = _user_id
  );
$$;

alter table teams enable row level security;
drop policy if exists "teams_owner" on teams;
create policy "teams_owner" on teams for all using (owner_id = auth.uid());
drop policy if exists "teams_member_read" on teams;
create policy "teams_member_read" on teams for select using (is_team_member(id, auth.uid()));

alter table team_members enable row level security;
drop policy if exists "team_members_owner_all" on team_members;
create policy "team_members_owner_all" on team_members for all using (is_team_owner(team_id, auth.uid()));
drop policy if exists "team_members_self_read" on team_members;
create policy "team_members_self_read" on team_members for select using (user_id = auth.uid());
drop policy if exists "lookup invite by token" on team_members;
create policy "lookup invite by token" on team_members for select using (invite_token is not null and status = 'pending');
drop policy if exists "accept own invite" on team_members;
create policy "accept own invite" on team_members for update using (invite_token is not null);

-- Team scan visibility (depends on team_members existing)
drop policy if exists "Team members can view team scans" on scans;
create policy "Team members can view team scans" on scans for select using (
  user_id = auth.uid() or user_id in (
    select tm2.user_id
    from team_members tm1
    join team_members tm2 on tm1.team_id = tm2.team_id
    where tm1.user_id = auth.uid() and tm1.status = 'active' and tm2.status = 'active'
  )
);

-- ── ADMIN: per-user activity report (dashboard "Users" panel) ──
drop function if exists get_user_activity();
create or replace function get_user_activity()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare result json;
begin
  if coalesce(auth.jwt() ->> 'email', '') not in ('sabahatghauri10@gmail.com', 'contact@vibesafe.info') then
    return json_build_object('error', 'not authorized');
  end if;
  select coalesce(json_agg(row_to_json(t)), '[]'::json) into result from (
    select
      coalesce(u.email, 'unknown') as email,
      count(*) filter (where e.event in ('scan_success','scan_failed')) as scans,
      count(*) filter (where e.event = 'scan_success') as ok,
      count(*) filter (where e.event = 'scan_failed') as fail,
      count(*) filter (where e.event in ('scan_success','scan_failed') and e.source in ('extension','vscode_extension','cursor')) as ext_scans,
      count(*) filter (where e.event in ('scan_success','scan_failed') and e.source = 'website') as web_scans,
      max(e.created_at) as last_active,
      min(e.created_at) as first_seen,
      (select p.plan from vibesafe_plans p where p.id = e.user_id) as plan,
      (select e2.extension_version from extension_events e2
        where e2.user_id = e.user_id and e2.extension_version is not null
        order by e2.created_at desc limit 1) as version
    from extension_events e
    left join auth.users u on u.id = e.user_id
    where e.user_id is not null
    group by e.user_id, u.email
    order by max(e.created_at) desc
    limit 200
  ) t;
  return result;
end;
$$;
grant execute on function get_user_activity() to authenticated;
