-- VibeSafe Continuous Monitoring — Team/Pro feature.
-- Users save live URLs to "watch"; a weekly Vercel Cron (api/monitor-scan.js)
-- re-scans each one, and emails the owner ONLY when security degrades
-- (score drops or a new critical appears). Idempotent: safe to re-run.

create table if not exists monitored_urls (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null,
  url           text not null,
  label         text,
  active        boolean not null default true,
  last_score    smallint,           -- score at the most recent scan
  last_criticals smallint,          -- critical count at the most recent scan
  last_scanned_at timestamptz,
  last_alert_at timestamptz,        -- when we last emailed about a degradation
  created_at    timestamptz not null default now(),
  unique (user_id, url)
);
alter table monitored_urls enable row level security;

-- Owners manage their own watched URLs from the dashboard.
drop policy if exists "monitored_urls_owner_all" on monitored_urls;
create policy "monitored_urls_owner_all" on monitored_urls
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── CRON: URLs due for a re-scan ──
-- Returns active watched URLs whose owner is on a paid plan and that haven't
-- been scanned in the last 6 days, with owner email + last snapshot for diffing.
drop function if exists get_urls_to_monitor();
create or replace function get_urls_to_monitor()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare result json;
begin
  select coalesce(json_agg(row_to_json(t)), '[]'::json) into result from (
    select
      m.id,
      m.user_id,
      m.url,
      m.label,
      m.last_score,
      m.last_criticals,
      u.email
    from monitored_urls m
    join auth.users u on u.id = m.user_id
    where m.active = true
      and coalesce((select p.plan from vibesafe_plans p where p.id = m.user_id), 'free') in ('pro', 'team')
      and (m.last_scanned_at is null or m.last_scanned_at < now() - interval '6 days')
    order by m.last_scanned_at asc nulls first
    limit 100
  ) t;
  return result;
end;
$$;
revoke execute on function get_urls_to_monitor() from public, anon, authenticated;
